name: test-ar

on: push

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"
          pip uninstall fold-core
          pip install https://github.com/dream-faster/fold/archive/main.zip
      - name: run-tests
        run: pytest tests/test_ar.py -s --durations 0
